export const FETCH_WECHAT_PUBLIC_LIST = 'FETCH_WECHAT_PUBLIC_LIST'
export const FETCH_INFO_BY_ID = 'FETCH_INFO_BY_ID'
export const UPDATE_WECHAT_PUBLIC_LIST = 'UPDATE_WECHAT_PUBLIC_LIST'
export const FETCH_WECHAT_PUBLIC_SELECT = 'FETCH_WECHAT_PUBLIC_SELECT'
export const ADD_WECHAT_PUBLIC_LIST = 'ADD_WECHAT_PUBLIC_LIST'
export const DELETE_WECHAT_PUBLIC_LIST = 'DELETE_WECHAT_PUBLIC_LIST'
export const UPDATE_ITEM_PRINT = 'UPDATE_ITEM_PRINT'

export const FETCH_WECHAT_MENU_LIST = 'FETCH_WECHAT_MENU_LIST'
export const ADD_WECHAT_MENU_LIST = 'ADD_WECHAT_MENU_LIST'
export const DELETE_WECHAT_MENU_LIST = 'DELETE_WECHAT_MENU_LIST'
export const UPDATE_WECHAT_MENU_LIST = 'UPDATE_WECHAT_MENU_LIST'
export const CHECK_WECHAT_MENU_LIST = 'CHECK_WECHAT_MENU_LIST'
export const UPDATE_WECHAT_MENU_STATUS = 'UPDATE_WECHAT_MENU_STATUS'
export const SYNC_WECHAT_MENU_STATUS = 'SYNC_WECHAT_MENU_STATUS'

export const UPDATE_MENU_ITEM_STATUS = 'UPDATE_MENU_ITEM_STATUS'

export const FETCH_WECHAT_REPLY_LIST = 'FETCH_WECHAT_REPLY_LIST'
export const ADD_WECHAT_REPLY_LIST = 'ADD_WECHAT_REPLY_LIST'
export const DELETE_WECHAT_REPLY_LIST = 'DELETE_WECHAT_REPLY_LIST'
export const UPDATE_WECHAT_REPLY_LIST = 'UPDATE_WECHAT_REPLY_LIST'
export const FETCH_WECHAT_REPLY_BYID = 'FETCH_WECHAT_REPLY_BYID'

export const FETCH_WECHAT_GROUP_LIST = 'FETCH_WECHAT_GROUP_LIST'
export const UPDATE_WECHAT_GROUP_LIST = 'UPDATE_WECHAT_GROUP_LIST'
export const DELETE_WECHAT_GROUP_LIST = 'DELETE_WECHAT_GROUP_LIST'
export const ADD_WECHAT_GROUP_LIST = 'ADD_WECHAT_GROUP_LIST'
export const FETCH_WECHAT_USERGROUP_LIST = 'FETCH_WECHAT_USERGROUP_LIST'

export const FETCH_WECHAT_USER_LIST = 'FETCH_WECHAT_USER_LIST'
export const FETCH_WECHAT_SINGER_USER = 'FETCH_WECHAT_SINGER_USER'

export const FETCH_WECHAT_CHANNEL_LIST = 'FETCH_WECHAT_CHANNEL_LIST'
export const SAVE_WECHAT_CHANNEL = 'SAVE_WECHAT_CHANNEL'
export const UPDATE_WECHAT_CHANNEL = 'UPDATE_WECHAT_CHANNEL'
export const DELETE_WECHAT_CHANNEL = 'DELETE_WECHAT_CHANNEL'

export const FETCH_WECHAT_SCENE_LIST = 'FETCH_WECHAT_SCENE_LIST'
export const SAVE_WECHAT_SCENE = 'SAVE_WECHAT_SCENE'
export const UPDATE_WECHAT_SCENE = 'UPDATE_WECHAT_SCENE'
export const DELETE_WECHAT_SCENE = 'DELETE_WECHAT_SCENE'

export const FETCH_WECHAT_POSITION_LIST = 'FETCH_WECHAT_POSITION_LIST'
export const SAVE_WECHAT_POSITION = 'SAVE_WECHAT_POSITION'
export const UPDATE_WECHAT_POSITION = 'UPDATE_WECHAT_POSITION'
export const DELETE_WECHAT_POSITION = 'DELETE_WECHAT_POSITION'

export const FETCH_WECHAT_QRCODE_SELECT = 'FETCH_WECHAT_QRCODE_SELECT'
export const FETCH_WECHAT_QRCODE_LIST = 'FETCH_WECHAT_QRCODE_LIST'
export const SAVE_WECHAT_QRCODE = 'SAVE_WECHAT_QRCODE'
export const UPDATE_WECHAT_QRCODE = 'UPDATE_WECHAT_QRCODE'
export const DELETE_WECHAT_QRCODE = 'DELETE_WECHAT_QRCODE'
export const ADD_WECHAT_SCENE = 'ADD_WECHAT_SCENE'
export const ADD_WECHAT_CHANNEL = 'ADD_WECHAT_CHANNEL'
export const ADD_WECHAT_GROUP = 'ADD_WECHAT_GROUP'
export const ADD_VIRTUAL_GROUP = 'ADD_VIRTUAL_GROUP'
export const ADD_WECHAT_POSITION = 'ADD_WECHAT_POSITION'

export const FETCH_WECHAT_MEDIA_LIST = 'FETCH_WECHAT_MEDIA_LIST'
export const FETCH_WECHAT_MEDIA_SELECT = 'FETCH_WECHAT_MEDIA_SELECT'
export const DELETE_WECHAT_MEDIA = 'DELETE_WECHAT_MEDIA'
export const FETCH_WECHAT_MEDIA_BYID = 'FETCH_WECHAT_MEDIA_BYID'
export const SAVE_WECHAT_MEDIA = 'SAVE_WECHAT_MEDIA'
export const UPDATE_WECHAT_MEDIA = 'UPDATE_WECHAT_MEDIA'
export const UPDATE_WECHAT_MEDIA_ID = 'UPDATE_WECHAT_MEDIA_ID'

export const FETCH_WECHAT_PICTURE_LIST = 'FETCH_WECHAT_PICTURE_LIST'
export const SAVE_WECHAT_PICTURE = 'SAVE_WECHAT_PICTURE'
export const UPDATE_WECHAT_PICTURE = 'UPDATE_WECHAT_PICTURE'
export const FETCH_WECHAT_PICTURE_BYID = 'FETCH_WECHAT_PICTURE_BYID'
export const DELETE_WECHAT_PICTURE_MATERIAL = 'DELETE_WECHAT_PICTURE_MATERIAL'

export const FETCH_WECHAT_SENDGROUP_LIST = 'FETCH_WECHAT_SENDGROUP_LIST'
export const FETCH_WECHAT_SENDGROUP_LIST_SELECT = 'FETCH_WECHAT_SENDGROUP_LIST_SELECT'
export const FETCH_WECHAT_SENDGROUP_MODAL_SELECT = 'FETCH_WECHAT_SENDGROUP_MODAL_SELECT'
export const SAVE_WECHAT_SENDGROUP_DATA = 'SAVE_WECHAT_SENDGROUP_DATA'
export const DELETE_WECHAT_SENDGROUP_DATA = 'DELETE_WECHAT_SENDGROUP_DATA'
export const UPDATE_WECHAT_SENDGROUP_DATA = 'UPDATE_WECHAT_SENDGROUP_DATA'
export const UPDATE_WECHAT_SENDGROUP_AUDIT = 'UPDATE_WECHAT_SENDGROUP_AUDIT'
export const UPDATE_WECHAT_MASS_STATUS = 'UPDATE_WECHAT_MASS_STATUS'
export const FETCH_WECHAT_MASS_PREVIEW = 'FETCH_WECHAT_MASS_PREVIEW'

export const FETCH_WECHAT_CUSTOMMENU_LIST = 'FETCH_WECHAT_CUSTOMMENU_LIST'
export const ADD_WECHAT_CUSTOMER = 'ADD_WECHAT_CUSTOMER'
export const UPDATE_WECHAT_CUSTOMER = 'UPDATE_WECHAT_CUSTOMER'
export const BIND_WECHAT_CUSTOMER = 'BIND_WECHAT_CUSTOMER'
export const DELETE_WECHAT_CUSTOMER = 'DELETE_WECHAT_CUSTOMER'

export const FETCH_WECHAT_CUSTOMMENURULE_LIST = 'FETCH_WECHAT_CUSTOMMENURULE_LIST'
export const FETCH_CITY_LIST = 'FETCH_CITY_LIST'
export const ADD_WECHAT_CUSTOMMENURULE_LIST = 'ADD_WECHAT_CUSTOMMENURULE_LIST'
export const DELETE_WECHAT_CUSTOMMENURULE_LIST = 'DELETE_WECHAT_CUSTOMMENURULE_LIST'
export const UPDATE_WECHAT_CUSTOMMENURULE_LIST = 'UPDATE_WECHAT_CUSTOMMENURULE_LIST'
export const SYNC_WECHAT_CUSTOMMENURULE_LIST = 'SYNC_WECHAT_CUSTOMMENURULE_LIST'

export const FETCH_WECHAT_CUSTOMMENUPKG_LIST = 'FETCH_WECHAT_CUSTOMMENUPKG_LIST'
export const DELETE_WECHAT_CUSTOMMENUPKG_LIST = 'DELETE_WECHAT_CUSTOMMENUPKG_LIST'
export const ADD_WECHAT_CUSTOMMENUPKG_LIST = 'ADD_WECHAT_CUSTOMMENUPKG_LIST'
export const UPDATE_WECHAT_CUSTOMMENUPKG_LIST = 'UPDATE_WECHAT_CUSTOMMENUPKG_LIST'
export const UPDATE_WECHAT_CUSTOMMENUPKG_STATUS = 'UPDATE_WECHAT_CUSTOMMENUPKG_STATUS'
export const UPDATE_WECHAT_CUSTOMMENUPKG_SORT = 'UPDATE_WECHAT_CUSTOMMENUPKG_SORT'

export const FETCH_WECHAT_CUSTOMER_LIST = 'FETCH_WECHAT_CUSTOMER_LIST'
export const ADD_WECHAT_CUSTOMMENU_LIST = 'ADD_WECHAT_CUSTOMMENU_LIST'
export const UPDATE_WECHAT_CUSTOMMENU_LIST = 'UPDATE_WECHAT_CUSTOMMENU_LIST'
export const DELETE_WECHAT_CUSTOMMENU_LIST = 'DELETE_WECHAT_CUSTOMMENU_LIST'

export const FETCH_WECHAT_CUSTOMERMANAGEMENT_LIST = 'FETCH_WECHAT_CUSTOMERMANAGEMENT_LIST'

export const FETCH_WECHAT_STATISTICAL_USER_LIST = 'FETCH_WECHAT_STATISTICAL_USER_LIST'
export const FETCH_WECHAT_STATISTICAL_USER_EXPORT = 'FETCH_WECHAT_STATISTICAL_USER_EXPORT'

export const FETCH_WECHAT_STATISTICAL_PICTURE_LIST = 'FETCH_WECHAT_STATISTICAL_PICTURE_LIST'
export const FETCH_WECHAT_STATISTICAL_PICTURE_DETAIL = 'FETCH_WECHAT_STATISTICAL_PICTURE_DETAIL'

export const FETCH_WECHAT_STATISTICAL_MESSAGE_LIST = 'FETCH_WECHAT_STATISTICAL_MESSAGE_LIST'

export const FETCH_WECHAT_STATISTICAL_MESSAGE_DETAIL = 'FETCH_WECHAT_STATISTICAL_MESSAGE_DETAIL'

export const FETCH_WECHAT_STATISTICAL_INTERFACE_LIST = 'FETCH_WECHAT_STATISTICAL_INTERFACE_LIST'

export const FETCH_WECHAT_CUSTOMERSTATISTICAL_LIST = 'FETCH_WECHAT_CUSTOMERSTATISTICAL_LIST'

export const FETCH_WECHAT_CUSTOMERSENDMESSAGE_LIST = 'FETCH_WECHAT_CUSTOMERSENDMESSAGE_LIST'
export const FETCH_WECHAT_CUSTOMER_MSG_SELECT = 'FETCH_WECHAT_CUSTOMER_MSG_SELECT'
export const SAVE_WECHAT_CUSTOMER_MSG = 'SAVE_WECHAT_CUSTOMER_MSG'
export const UPDATE_WECHAT_CUSTOMER_MSG = 'UPDATE_WECHAT_CUSTOMER_MSG'
export const DELETE_WECHAT_CUSTOMER_MSG = 'DELETE_WECHAT_CUSTOMER_MSG'
export const FETCH_WECHAT_CUSTOMER_BYID = 'FETCH_WECHAT_CUSTOMER_BYID'

export const FETCH_WECHAT_ERRORLOG_LIST = 'FETCH_WECHAT_ERRORLOG_LIST'


export const FETCH_SENDGROUP_PREVIEW = 'FETCH_SENDGROUP_PREVIEW'
export const DELETE_SENDGROUP_PREVIEW = 'DELETE_SENDGROUP_PREVIEW'

//用户消息
export const FETCH_USERMESSAGE_LIST = 'FETCH_USERMESSAGE_LIST'
export const FETCH_WECHAT_REPLY_DATA = 'FETCH_WECHAT_REPLY_DATA'
export const FETCH_WECHAT_REPLY_SELECT = 'FETCH_WECHAT_REPLY_SELECT'
export const FETCH_WECHAT_KEYWORD_REPLY = 'FETCH_WECHAT_KEYWORD_REPLY'

//事件消息
export const FETCH_EVENTMESSAGE_LIST = 'FETCH_EVENTMESSAGE_LIST'
export const FETCH_WECHAT_EVENT_REPLY_SELECT = 'FETCH_WECHAT_EVENT_REPLY_SELECT'
export const FETCH_WECHAT_EVENT_REPLY_DATA = 'FETCH_WECHAT_EVENT_REPLY_DATA'
export const FETCH_WECHAT_KEYWORD_EVENT_REPLY = 'FETCH_WECHAT_KEYWORD_EVENT_REPLY'
